version: "2"
services:
  db:
    container_name: db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    env_file: .env
